version: 0.2

env:
  variables:
    PORT: "3000"
phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo $AWS_ACCOUNT_ID AWS_ACCOUNT_ID
      - echo $AWS_ACCOUNT_REGION AWS_ACCOUNT_REGION
      - echo $IMAGE_REPO_NAME IMAGE_REPO_NAME
      - echo $IMAGE_TAG IMAGE_TAG
      - aws --version
      - echo Logging in to Amazon ECR...
      # - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 334033517520.dkr.ecr.eu-west-1.amazonaws.com/exchangr
      - REPOSITORY_URI=334033517520.dkr.ecr.eu-west-1.amazonaws.com/exchangr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMI_HASH:=latest}
      - IMAGE_REPO_NAME='exchangr'
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG