version: 0.2

env:
  variables:
    PORT: "3000"
phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo $AWS_ACCOUNT_ID AWS_ACCOUNT_ID
      - echo $AWS_ACCOUNT_REGION AWS_ACCOUNT_REGION
      - echo $IMAGE_REPO_NAME IMAGE_REPO_NAME
      - echo $IMAGE_TAG IMAGE_TAG
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG