version: 0.2

env:
  PORT:3000
phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
# artifacts:
#  files:
#    - target/messageUtil-1.0.jar